### ISSUE TITLE
Can't install impatience from extensions.gnome.org on Gnome 3.16.2

### ISSUE THREAD

**Issue by Paviluf** [gfxmonk/gnome-shell-impatience#9]
Hello,

I can't install impatience from extensions.gnome.org on Ubuntu 15.04 (uptated to Gnome 3.16.2 with the Gnome 3 staging ppa).

Extensions.gnome.org don't show the extension, like it's not compatible with my Gnome Shell version.

Thank you

**Comment by gfxmonk** [comment]
Ahh, my apologies. It's compatible, but I forgot to upload it to extensions.gnome.org (I run a few extensions, and that step is both tedious and forgettable). You can run it from a git checkout if you're impatient (see what I did there?) for now, otherwise it'll work from extensions.gnome.org once the latest version passes review.

**Comment by Paviluf** [comment]
I can wait a little so I will install it from extensions.gnome.org when it's available.
Thank you very much.

**Comment by gfxmonk** [comment]
It's up! (that was a quick review, I've had them take weeks in the past)

**Comment by Paviluf** [comment]
You are right, extensions.gnome.org has been updated and that works.
Thank you again.
